# Generated by Django 2.2.12 on 2020-04-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('sige', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='')),
                ('responsavel', models.CharField(max_length=20)),
                ('fone_responsavel', models.IntegerField()),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
