# Generated by Django 2.2.12 on 2020-04-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisadis', '0002_auto_20200407_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='fone_responsavel',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sige',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
